#3 style: 파일 명칭 통합 수정
OpenSourceSW-Cub/server pull request #7
Opened 2022-12-14 13:43 UTC by listenyoon

## 📢 관련 이슈
- [x] #3 

## 📃 작업 사항
- Model, Controller, Service의 hp 이름을 helper로 통일하고 import문과 객체 이름을 수정하였습니다.

2022-12-14 13:44 UTC, Suanna01 reviewed
확인해보겠습니다!

2022-12-15 04:28 UTC, Suanna01 requested changes
hp가 아닌 helper로 통일성을 주어야 나중에 다른 사람이 봤을 때 이해하기 쉽고 전체 코드의 통일감이 있을 거 같습니다!

2022-12-15 04:28 UTC, Suanna01 commented on src/routers/helper.apply.router.js
> +const hpApplyRouter = (router)=>{
hpApplyRouter -> helperApplyRouter 로 바꿔주세요!

2022-12-15 04:28 UTC, Suanna01 commented
> 수정할 파일들이 굉장히 많았는데 오류없이 완벽히 하신 것 같습니다! 수고 많으셨습니다!

2022-12-15 04:29 UTC, listenyoon commented on src/routers/helper.apply.router.js
> +const hpApplyRouter = (router)=>{
넵~

2022-12-15 04:36 UTC, Suanna01 reviewed
좋습니다! 이제 전체적으로 명칭이 통일되어 깔끔하네요! 수고하셨습니다~

2022-12-15 04:37 UTC, merged